Fixed compatibility with UE 4.22.3
yas-online/UE4-DedicatedServer pull request #4
Opened 2019-07-01 18:27 UTC by Scienziatogm

2019-07-01 20:19 UTC, neico requested changes
Left some nitpicks (I'd like to keep the code style consistent) as I can't validate if the code works fine with those changes and trust you on that and therefore focused on the actual diff's instead.

Also, while we're at it, maybe update the link reference at `DumpConsoleHelp()` to `https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Engine/Private/UnrealEngine.cpp#L4260`?

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/DedicatedServer.cpp
> +				g_pConsole = TUniquePtr<FServerConsole>(new FServerConsole());
```suggestion
				g_pConsole = TUniquePtr<FServerConsole>( new FServerConsole() );
```

2019-07-01 20:19 UTC, neico commented on Source/RCon/RCon.Build.cs
> +	public RCon(ReadOnlyTargetRules Target) : base(Target)
```suggestion
	public RCon( ReadOnlyTargetRules Target ) : base( Target )
```

2019-07-01 20:19 UTC, neico commented on Source/RCon/RCon.Build.cs
> +    {
```suggestion
	{
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/DedicatedServer.Build.cs
> +	public DedicatedServer(ReadOnlyTargetRules Target) : base(Target)
```suggestion
	public DedicatedServer( ReadOnlyTargetRules Target ) : base( Target )
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/DedicatedServer.Build.cs
> +    {
```suggestion
	{
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Public/ServerConsole.h
> +	class FServerConsole : public FOutputDeviceConsole
If you remove `FOutputDeviceConsolePlatform` here then you might as well remove it generally, at a glance it doesn't look like I've used anything that isn't present in `FOutputDevice`

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +					});
```suggestion
					} );
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +						TCHAR sOutput[MAX_SPRINTF] = TEXT("");
```suggestion
						TCHAR sOutput[MAX_SPRINTF] = TEXT( "" );
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +					AsyncTask(ENamedThreads::GameThread, [this, tmp]() {
```suggestion
					AsyncTask( ENamedThreads::GameThread, [this, sInput]()
					{
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +					auto& tmp = m_sInput;
```suggestion
					auto &sInput = m_sInput;
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +						if( tmp.StartsWith( TEXT( "help" ) ) )
```suggestion
						if( sInput.StartsWith( TEXT( "help" ) ) )
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +							m_hCommandHistory.Add( tmp );
```suggestion
							m_hCommandHistory.Add( sInput );
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +							FCString::Sprintf( sOutput, TEXT( "> %s%s" ), *tmp, LINE_TERMINATOR );
```suggestion
							FCString::Sprintf( sOutput, TEXT( "> %s%s" ), *sInput, LINE_TERMINATOR );
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +						else if( GEngine->Exec( GWorld, *tmp ) )
```suggestion
						else if( GEngine->Exec( GWorld, *sInput ) )
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +							FCString::Sprintf( sOutput, TEXT( "> %s%s" ), *tmp, LINE_TERMINATOR );
```suggestion
							FCString::Sprintf( sOutput, TEXT( "> %s%s" ), *sInput, LINE_TERMINATOR );
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +							m_hCommandHistory.Add( tmp );
```suggestion
							m_hCommandHistory.Add( sInput );
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +						else if ( GWorld->GetAuthGameMode() != nullptr && GWorld->GetAuthGameMode()->ProcessConsoleExec(*tmp, *GLog, nullptr) )
```suggestion
						else if ( GWorld->GetAuthGameMode() != nullptr && GWorld->GetAuthGameMode()->ProcessConsoleExec( *sInput, *GLog, nullptr ) )
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +							FCString::Sprintf(sOutput, TEXT("> %s%s"), *tmp, LINE_TERMINATOR);
```suggestion
							FCString::Sprintf( sOutput, TEXT("> %s%s"), *sInput, LINE_TERMINATOR );
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +							::WriteConsole(m_hOutputHandle, sOutput, FCString::Strlen(sOutput), &iCharsWritten, NULL);
```suggestion
							::WriteConsole( m_hOutputHandle, sOutput, FCString::Strlen( sOutput ), &iCharsWritten, NULL );
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +							m_hCommandHistory.Add(tmp);
```suggestion
							m_hCommandHistory.Add( sInput );
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +							FCString::Sprintf( sOutput, TEXT( "Unknown Command: %s%s" ), *tmp, LINE_TERMINATOR );
```suggestion
							FCString::Sprintf( sOutput, TEXT( "Unknown Command: %s%s" ), *sInput, LINE_TERMINATOR );
```

2019-07-01 20:19 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +						unsigned long iCharsWritten;
```suggestion
						unsigned long iCharsWritten = 0;
```
It's not really used, but I guess initializing it isn't such a bad idea anyway (not sure, but maybe `&iCharsWritten` could be changed to `nullptr` or simply 0 in that case, I don't think that crossed my mind back then...)

2019-07-01 23:12 UTC, Scienziatogm commented
Ok, I changed the code to follow your suggestions. I have tested this on Windows platform and everything works fine, while on Linux platform I'm getting some errors on which I'll work tomorrow. I haven't a Mac computer, so I cannot test the code on Mac platforms. Anyway after everything works I'll try to implement the Rcon feature and the autocompletion via tab feature.

2019-07-02 05:16 UTC, neico commented
You missed a `FOutputDeviceConsolePlatform` at ServerConsole.cpp: https://github.com/yas-online/UE4-DedicatedServer/pull/4/files#diff-75bef9b81fb98d7876bf9aae65810effR58

2019-07-02 08:50 UTC, Scienziatogm commented
> You missed a `FOutputDeviceConsolePlatform` at [ServerConsole.cpp](https://github.com/yas-online/UE4-DedicatedServer/pull/4/files#diff-75bef9b81fb98d7876bf9aae65810effR58)

Done in 82ec0eee2de09448b585a44590a598f590e4ac21

2019-07-02 09:01 UTC, Scienziatogm commented
Seems like SetColor is a member of FOutputDeviceConsoleWindows, so it gives compile errros.

2019-07-02 22:03 UTC, Scienziatogm commented
Everything seems to work now since I restored platform specific output devices, but today I've been working on the Linux console. When I finish, I'll make a commit. 😄

2019-07-03 08:29 UTC, neico approved these changes

2019-07-03 08:30 UTC, neico commented
I think we can make a new PR for adding support for linux I guess

But this one seems ok so far, so I guess we can merge it?

2019-07-03 08:52 UTC, Scienziatogm commented
> I think we can make a new PR for adding support for linux I guess
> 
> But this one seems ok so far, so I guess we can merge it?

Yes, if you want. When I finish the Linux support, I'll make another pull request.

2019-07-03 10:23 UTC, merged