Fixes building issues with 4.24
yas-online/UE4-DedicatedServer pull request #8
Opened 2020-03-10 18:41 UTC by alexandrosk0

Fixes building issues with 4.24.

2020-03-10 20:34 UTC, neico requested changes
Mostly style related changes, the rest should be ok at least.

2020-03-10 20:34 UTC, neico commented on Source/DedicatedServer/Private/DedicatedServer.cpp
> +											RequestEngineExit(TEXT("The server is outdated"));
```suggestion
											RequestEngineExit( TEXT( "The server is outdated" ) );
```

2020-03-10 20:34 UTC, neico commented on Source/DedicatedServer/Private/ServerConsoleWindows.cpp
> +		hCursorPosition.X = hCursorPosition.Y = 0;
```suggestion
		COORD hCursorPosition = {};
```

2020-03-11 04:23 UTC, alexandrosk0 commented
My bad for adding the autocompletion in this pull request.

2020-03-11 09:28 UTC, neico approved these changes

2020-03-11 09:30 UTC, merged